[pytest]
markers =
    cuda: the test requires a graphical processing unit (GPU) to run
    heavy: the test takes long to compute
    real: calls real external service
    plot: draws an image
asyncio_mode=auto
asyncio_default_fixture_loop_scope=function
